FROM arm64v8/ubuntu:jammy

SHELL ["/bin/bash", "-c"]

# Set the environment to non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -q && \
    apt-get install -y apt-utils

RUN rm /etc/apt/apt.conf.d/docker-clean

ARG ROS_DISTRO=humble
ARG INSTALL_PACKAGE=desktop

# --- Install ROS 2 Humble ---
RUN apt update -q && \
    apt install -y curl gnupg2 lsb-release  && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    apt-get update -q && \
    apt-get install -y ros-${ROS_DISTRO}-${INSTALL_PACKAGE} \
    python3-argcomplete \
    python3-colcon-common-extensions \
    python3-rosdep python3-vcstool

# --- Common tools ---
RUN apt-get update && apt-get install -y net-tools \
    iputils-ping\
    snapd \
    git \
    tmux \
    vim \
    nano \
    wget \
    software-properties-common \
    python3-pip && \
    python3 -m pip install transforms3d websocket-client catmux distro && \
    rosdep init && \
    rm -rf /var/lib/apt/lists/*

# --- Additional ROS 2 packages ---
RUN apt-get update -q && \
    apt-get install -y \
    ros-humble-tf-transformations \
    ros-humble-rqt* \
    ros-humble-pointcloud-to-laserscan && \
    echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

# --- CycloneDDS and PCL ---
RUN apt-get update -q && \
    apt-get install -y \
    ros-humble-rosidl-generator-dds-idl \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-pcl-conversions \
    ros-humble-pcl-ros

# --- Livox SDK2 (required by some sensor packages) ---
RUN git clone https://github.com/Livox-SDK/Livox-SDK2.git && \
    cd ./Livox-SDK2 && \
    mkdir build  && \
    cd build && \
    cmake .. && make -j && \
    make install && \
    cd ../.. && \
    rm -rf Livox-SDK2

RUN apt-get update && apt-get install -y net-tools \
    libpcap-dev

# --- koide3 PPA for GLIM dependencies ---
RUN curl -s https://koide3.github.io/ppa/setup_ppa.sh | bash

# --- Install GLIM dependencies + GLIM ROS 2 ---
# Default: CUDA 12.2 build for Jetson Orin NX
# Change to ros-humble-glim-ros for CPU-only, or
# ros-humble-glim-ros-cuda12.6 for newer CUDA
ARG GLIM_PACKAGE=ros-humble-glim-ros-cuda12.2
RUN apt-get update && apt-get install -y \
    libiridescence-dev \
    libboost-all-dev \
    libglfw3-dev \
    libmetis-dev \
    libgtsam-points-cuda12.2-dev \
    ${GLIM_PACKAGE} && \
    ldconfig && \
    rm -rf /var/lib/apt/lists/*
